{
 "title": "Solar",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(meter_frequency_hertz{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Prod today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    { "expr": "production_today_watthours" }
   ]
  },
  {
   "title": "Cons today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"}"
    }
   ]
  },
  {
   "title": "Net today",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"} - ignoring(type) production_today_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Prod 7 days",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    { "expr": "production_7days_watthours" }
   ]
  },
  {
   "title": "Cons 7 days",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"}"
    }
   ]
  },
  {
   "title": "Net 7day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"} - ignoring(type) production_7days_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Production Lifetime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "expr": "production_lifetime_watthours{type=\"eim\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(meter_voltage_volts{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Production meter power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 2, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(phase) (meter_active_power_watts{type=\"production\"})",
     "legendFormat": "Active power {{phase}}"
    },
    {
     "expr": "sum by(phase, type) (meter_apparent_power_watts{type=\"production\"})",
     "legendFormat": "Apparent power {{phase}}"
    },
    {
     "expr": "sum by(phase, type) (meter_reactive_power_watts{type=\"production\"})",
     "legendFormat": "Reactive power {{phase}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 3 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "sum by(phase)(meter_current_amps{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(meter_active_power_watts{type=\"total-consumption\"})"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(meter_power_factor_ratio{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Net Consumption",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 7 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(meter_active_power_watts{type=\"net-consumption\"})"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum by(type) (power_now_watts)" }
   ]
  },
  {
   "title": "Power Factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(phase) (meter_power_factor_ratio{type=\"production\"})",
     "legendFormat": "Power Factor {{phase}}"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 11 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(meter_active_power_watts{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Net Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(meter_active_power_watts{type=\"net-consumption\"})"
    }
   ]
  },
  {
   "title": "Average power by inverter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(serial, location) (inverter_last_report_watts)",
     "legendFormat": "{{location}} {{serial}}"
    },
    {
     "expr": "max (inverter_max_report_watts)"
    }
   ]
  },
  {
   "title": "Total Consumption",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (meter_active_power_watts{type=\"total-consumption\"})"
    }
   ]
  },
  {
   "title": "Total power by array",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(location) (inverter_last_report_watts)"
    },
    {
     "expr": "max(sum by(location) (inverter_max_report_watts))",
     "legendFormat": "Max per array power"
    }
   ]
  },
  {
   "title": "Total production",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum (meter_active_power_watts{type=\"production\"})"
    }
   ]
  },
  {
   "title": "Net consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumption_today_watthours{type=\"total-consumption\"} - ignoring(type) production_today_watthours{type=\"eim\"}"
    },
    {
     "expr": "consumption_7days_watthours{type=\"total-consumption\"} - ignoring(type) production_7days_watthours{type=\"eim\"}"
    }
   ]
  }
 ]
}